export const EVIDENCE_ROUTES = Object.freeze({
  ARCHIVE: "archive",
  LIVE: "live",
  BOTH: "both",
  NEITHER: "neither",
});

export const EVIDENCE_ROUTING_POLICY = Object.freeze({
  archive: "Use archived history for prior intent, rationale, exact wording, decisions, rejected approaches, continuity, and scope disputes.",
  live: "Use live tools for current files, runtime behavior, configuration, test results, and task status. Mentioning old discussion or inviting history lookup does not make archive evidence material when the answer is exclusively current mutable state.",
  both: "For mixed questions, recover archived intent first, inspect live state second, and explicitly reconcile conflicts. Live inspection is authoritative for mutable current state.",
  neither: "Do not retrieve when the needed evidence is already in recent context or the question needs neither historical nor live project evidence. Avoid speculative broad archive searches.",
});

export const SEARCH_TOOL_DESCRIPTION =
  "Find historical evidence candidates from earlier context. Trigger a search when the request references a concrete but currently-invisible referent — a named file, symbol, error string, commit or PR, specific value, or a prior decision, agreement, or scope item — that is not present in the visible context, or uses back-references (\"earlier\", \"before\", \"originally\", \"we agreed\", \"that/those\") pointing to content that has rotated out; also search before asserting a specific earlier detail you cannot currently see. When a project-specific term is not defined in visible context and you are about to search the repository, documentation, web, or another live source to understand it, also search the archive for that exact term and treat its origin as ambiguous until archived and live evidence resolve it. A continuity marker confirms only that eligible earlier discussion matched an exact anchor copied from the current user message. When the answer depends on that prior project-specific meaning, search the marker's exact anchor before using it; the marker is not evidence that any archived assertion is true. Use context_recall on a result id for exact original wording or source evidence. Use live tools—not the archive—for current mutable state. For mixed questions, recover archived intent first, then inspect live state and reconcile conflicts. Historical framing or an invitation to search history does not make archive evidence material for an exclusively current question. Naming a concept does not by itself mean it is archived: when a referent's location is ambiguous (it may be prior conversation or current repository state), probe both rather than assuming the archive. Avoid speculative broad searches; key each search on a concrete anchor (file name, symbol, error text, decision term). For a conceptually phrased historical question without an exact identifier, put 3–8 concise likely synonyms or domain terms in one query so lexical search can match alternate wording. Search exact file names, symbols, error strings, commits, PRs, and specific values verbatim first; do not broaden those anchors. If a conceptually phrased archive-required search misses, make at most one reformulated search with likely alternate wording. An empty result for a well-anchored query is itself routing evidence: treat the referent as live or external and probe repository, docs, or MCP next instead of retrying broader archive searches.";

export const RECALL_TOOL_DESCRIPTION =
  "Recover one exact archived source document by an id from context_window_search or an archive marker. Use for exact original wording or source evidence, not as proof of current mutable state; verify current state with live tools.";

export const SUPERSEDE_TOOL_DESCRIPTION =
  "Mark a prior archived decision or document as superseded by a correction. Use when the user reverses an earlier decision so search and automatic retrieval stop treating the old version as live. Prefer writing durable constraints into the repository (AGENTS.md, ADR, config) rather than pinning archive records.";

export const EVIDENCE_ROUTING_GUIDELINES = Object.freeze([
  "Before answering, classify the evidence needed: already in visible context (answer directly), current mutable project state (use live tools), or an out-of-window referent such as prior intent, rationale, decisions, rejected approaches, continuity, or scope disputes (use context_window_search); combine archive and live only when both are required.",
  "Use context_recall—not task records or assistant summaries—when exact original wording or source evidence is required; recall only ids returned by context_window_search or archive markers.",
  "Do not use context_window_search or context_recall as proof of current files, runtime behavior, configuration, tests, or task status; use live tools, and note that historical framing or an invitation to search history does not make archive evidence material for an exclusively current question.",
  "For mixed questions, use context_window_search and, when source precision matters, context_recall to recover archived intent first; then inspect live state and reconcile conflicts, treating live evidence as authoritative for mutable state.",
  "Skip context_window_search and context_recall when evidence is already in recent context or neither historical nor live project evidence is needed; avoid speculative broad archive searches. Treat an empty result for a well-anchored query as routing evidence that the referent is likely live or external—probe repository, docs, or MCP next rather than retrying broader searches.",
  "Naming a concept does not imply it is archived; when a referent's location is ambiguous between rotated-out conversation and current repository state, use both context_window_search and live inspection to locate it. When a project-specific term is not defined in visible context and you are about to search the repository, documentation, web, or another live source to understand it, also run context_window_search for the exact term, treating its origin as ambiguous until archived and live evidence resolve it.",
  "Before you quote or assert a specific earlier detail (a number, name, exact phrasing, or committed decision) not visible in the current context, run context_window_search for its anchor rather than reconstructing it from memory. A continuity marker only confirms that eligible earlier discussion matched the quoted anchor from the current user message; if prior project-specific meaning is material, search that exact anchor before answering, and do not treat the marker itself as a recovered fact, decision, definition, or current-state claim.",
  "Do not introduce terminology found only in an archive candidate returned by context_window_search or context_recall as if the user already knows it. Omit it unless it is necessary; when necessary, define it in plain language and identify whether it came from archived discussion or a live source.",
  "When context_window_search has no exact identifier for a conceptually phrased historical question, include 3–8 concise likely synonyms or domain terms in one query; search exact file names, symbols, error strings, commits, PRs, and specific values verbatim first and never broaden those anchors. If a conceptual archive-required search misses, make at most one reformulated context_window_search call with likely alternate wording.",
  "When the user reverses a prior archived decision, call context_window_supersede (or admit the new decision with supersedes) so the old version leaves search; do not leave both as equal live hits.",
  "When a decision or constraint must outlive the archive retention window (cross-session process, security, standing project rule), write it into the repository (AGENTS.md, CLAUDE.md, ADR, or config). The archive is provenance, not the system of record; do not pin archive documents for longevity.",
]);

export const ARCHIVED_EVIDENCE_LABEL =
  "Archived historical evidence — may be stale about current mutable state; verify live state separately.";
